### ISSUE TITLE
android编译文件的修改

### ISSUE THREAD

**Issue by chenjianjun571** [befovy/ijkplayer#17]
android/ijkplayer/ijkplayer-armv7a/src/main/jni 下面的Android.mk需要修改，否则编译会出错。
MY_APP_FFMPEG_OUTPUT_PATH
![image](https://user-images.githubusercontent.com/4081496/77634838-9985aa80-6f8c-11ea-87c0-e74c4edde842.png)

**Comment by befovy** [comment]
这个项目用的是 cmake 配置 NDK 编译。没有使用 Android.mk 这种方式

**Comment by chenjianjun571** [comment]
大神能否告知一下cmake的编译方式；修改了一点代码，需要重新编译验证。谢谢

**Comment by befovy** [comment]
https://github.com/befovy/ijkplayer#build-android-via-cmake

./gradlew :fijkplayer-full:assembleRelease

gradle 关联了 cmake，执行 gradle 编译就可以
