### ISSUE TITLE
断网重连、循环播放是否支持

### ISSUE THREAD

**Issue by imtianx** [befovy/ijkplayer#29]
`ijkplayer` 好像支持断网重连，需在 `url` 前添加 `ijkhttphook:`，但是在测试的时候发现无效.

**Comment by befovy** [comment]
这个 fork 的 ijkplayer 没有在这方面进行修改。如果 ijkplayer 支持，那 befovy/ijkplayer 肯定也是支持的。
是不是在使用上有些什么差别

**Comment by imtianx** [comment]
循环播放是支持的，之前设置有问题😂，断网重连 对 mp4也是可以的，flv 的就不支持了，目前想到的是网络可用时重新初始化播放器然后播放来解决。
