### ISSUE TITLE
ijkffmpeg: LOCAL_SRC_FILES points to a missing file

### ISSUE THREAD

**Issue by zinwalin** [befovy/ijkplayer#34]
➜ /Users/michael/Development/befovy_ijkplayer/android/contrib git:(master) >./compile-ffmpeg.sh all

![image](https://user-images.githubusercontent.com/5416196/83005287-31fae280-a043-11ea-9931-e5ec716a146b.png)

➜ /Users/michael/Development/befovy_ijkplayer/android git:(master) >sh compile-ijk.sh

![image](https://user-images.githubusercontent.com/5416196/83005370-4e971a80-a043-11ea-8ec7-d24c7ab946b7.png)

是不是MY_APP_FFMPEG_OUTPUT_PATH变量配置有问题？

**Comment by zinwalin** [comment]
> 不需要 sh compile-ijk.sh
> 
> 编译完成 ffmpeg 之后，打开 android studio 就可以直接运行了

![image](https://user-images.githubusercontent.com/5416196/83137622-10b9f500-a11c-11ea-917c-7a7f0c9e8f8c.png)

**Comment by befovy** [comment]
please use the latest build script
https://github.com/befovy/ijkplayer/blob/master/.github/workflows/android.yml shows how to build boringssl libsrt ffmpeg and ijkplayer
