### ISSUE TITLE
ABIs [armeabi] are not supported for platform. Supported ABIs are [arm64-v8a, armeabi-v7a, x86, x86_64].

### ISSUE THREAD

**Issue by zinwalin** [befovy/ijkplayer#35]
![image](https://user-images.githubusercontent.com/5416196/83394136-9e525900-a42a-11ea-841f-84b6658b020d.png)

**Comment by befovy** [comment]
please use the latest build script
https://github.com/befovy/ijkplayer/blob/master/.github/workflows/android.yml shows how to build boringssl libsrt ffmpeg and ijkplayer

**Comment by befovy** [comment]
armeabi support is removed
