### ISSUE TITLE
build ./compile-libsrt.sh error

### ISSUE THREAD

**Issue by samychen** [befovy/ijkplayer#37]
log info:
Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler: /Users/samychen/Develop/android-ndk-r15c/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-gcc 
Build flags: ;-fPIE;-fPIC
Id flags:  

The output was:
1
/Users/samychen/Develop/android-ndk-r15c/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot open crtbegin_dynamic.o: No such file or directory
/Users/samychen/Develop/android-ndk-r15c/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot open crtend_android.o: No such file or directory
/Users/samychen/Develop/android-ndk-r15c/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lc
/Users/samychen/Develop/android-ndk-r15c/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -ldl
collect2: error: ld returned 1 exit status

Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
Compiler: /Users/samychen/Develop/android-ndk-r15c/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-g++ 
Build flags: 
Id flags:  

The output was:
1
/Users/samychen/Develop/android-ndk-r15c/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot open crtbegin_dynamic.o: No such file or directory
/Users/samychen/Develop/android-ndk-r15c/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot open crtend_android.o: No such file or directory
/Users/samychen/Develop/android-ndk-r15c/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lstdc++
/Users/samychen/Develop/android-ndk-r15c/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lm
/Users/samychen/Develop/android-ndk-r15c/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lc
/Users/samychen/Develop/android-ndk-r15c/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -ldl
collect2: error: ld returned 1 exit status

Performing C SOURCE FILE Test CMAKE_HAVE_LIBC_PTHREAD failed with the following output:
Change Dir: /Users/samychen/AndroidStudioProjects/ijkplayer/android/contrib/libsrt-armv7a/CMakeFiles/CMakeTmp

Run Build Command(s):/Users/samychen/AndroidStudioProjects/ijkplayer/android/contrib/build/toolchain-armv7a/bin/make cmTC_17b0b/fast && /Users/samychen/AndroidStudioProjects/ijkplayer/android/contrib/build/toolchain-armv7a/bin/make -f CMakeFiles/cmTC_17b0b.dir/build.make CMakeFiles/cmTC_17b0b.dir/build
make[1]: Entering directory `/Users/samychen/AndroidStudioProjects/ijkplayer/android/contrib/libsrt-armv7a/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_17b0b.dir/src.c.o
/Users/samychen/Develop/android-ndk-r15c/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-gcc --sysroot=/Users/samychen/Develop/android-ndk-r15c/sysroot  -isystem /Users/samychen/Develop/android-ndk-r15c/sysroot/usr/include -isystem /Users/samychen/Develop/android-ndk-r15c/sysroot/usr/include/arm-linux-androideabi  -fPIE -fPIC    -march=armv7-a -mthumb -mfpu=vfpv3-d16 -mfloat-abi=softfp -funwind-tables -no-canonical-prefixes -D__ANDROID_API__=14 -fexceptions -DCMAKE_HAVE_LIBC_PTHREAD -g   -o CMakeFiles/cmTC_17b0b.dir/src.c.o   -c /Users/samychen/AndroidStudioProjects/ijkplayer/android/contrib/libsrt-armv7a/CMakeFiles/CMakeTmp/src.c
Linking C executable cmTC_17b0b
/usr/local/Cellar/cmake/3.17.0_1/bin/cmake -E cmake_link_script CMakeFiles/cmTC_17b0b.dir/link.txt --verbose=1
/Users/samychen/Develop/android-ndk-r15c/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-gcc --sysroot=/Users/samychen/Develop/android-ndk-r15c/platforms/android-14/arch-arm -fPIE -fPIC    -march=armv7-a -mthumb -mfpu=vfpv3-d16 -mfloat-abi=softfp -funwind-tables -no-canonical-prefixes -D__ANDROID_API__=14 -fexceptions -DCMAKE_HAVE_LIBC_PTHREAD -g  -Wl,--fix-cortex-a8  -Wl,--gc-sections -Wl,-z,nocopyreloc  -pie  CMakeFiles/cmTC_17b0b.dir/src.c.o  -o cmTC_17b0b 
/Users/samychen/AndroidStudioProjects/ijkplayer/android/contrib/libsrt-armv7a/CMakeFiles/CMakeTmp/src.c:13: error: undefined reference to 'pthread_cancel'
collect2: error: ld returned 1 exit status
make[1]: *** [cmTC_17b0b] Error 1
make[1]: Leaving directory `/Users/samychen/AndroidStudioProjects/ijkplayer/android/contrib/libsrt-armv7a/CMakeFiles/CMakeTmp'
make: *** [cmTC_17b0b/fast] Error 2

Source file was:
#include <pthread.h>

void* test_func(void* data)
{
  return data;
}

int main(void)
{
  pthread_t thread;
  pthread_create(&thread, NULL, test_func, NULL);
  pthread_detach(thread);
  pthread_cancel(thread);
  pthread_join(thread, NULL);
  pthread_atfork(NULL, NULL, NULL);
  pthread_exit(NULL);

  return 0;
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /Users/samychen/AndroidStudioProjects/ijkplayer/android/contrib/libsrt-armv7a/CMakeFiles/CMakeTmp

Run Build Command(s):/Users/samychen/AndroidStudioProjects/ijkplayer/android/contrib/build/toolchain-armv7a/bin/make cmTC_37662/fast && /Users/samychen/AndroidStudioProjects/ijkplayer/android/contrib/build/toolchain-armv7a/bin/make -f CMakeFiles/cmTC_37662.dir/build.make CMakeFiles/cmTC_37662.dir/build
make[1]: Entering directory `/Users/samychen/AndroidStudioProjects/ijkplayer/android/contrib/libsrt-armv7a/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_37662.dir/CheckFunctionExists.c.o
/Users/samychen/Develop/android-ndk-r15c/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-gcc --sysroot=/Users/samychen/Develop/android-ndk-r15c/sysroot  -isystem /Users/samychen/Develop/android-ndk-r15c/sysroot/usr/include -isystem /Users/samychen/Develop/android-ndk-r15c/sysroot/usr/include/arm-linux-androideabi  -fPIE -fPIC    -march=armv7-a -mthumb -mfpu=vfpv3-d16 -mfloat-abi=softfp -funwind-tables -no-canonical-prefixes -D__ANDROID_API__=14 -fexceptions -DCHECK_FUNCTION_EXISTS=pthread_create -g   -o CMakeFiles/cmTC_37662.dir/CheckFunctionExists.c.o   -c /usr/local/Cellar/cmake/3.17.0_1/share/cmake/Modules/CheckFunctionExists.c
Linking C executable cmTC_37662
/usr/local/Cellar/cmake/3.17.0_1/bin/cmake -E cmake_link_script CMakeFiles/cmTC_37662.dir/link.txt --verbose=1
/Users/samychen/Develop/android-ndk-r15c/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-gcc --sysroot=/Users/samychen/Develop/android-ndk-r15c/platforms/android-14/arch-arm -fPIE -fPIC    -march=armv7-a -mthumb -mfpu=vfpv3-d16 -mfloat-abi=softfp -funwind-tables -no-canonical-prefixes -D__ANDROID_API__=14 -fexceptions -DCHECK_FUNCTION_EXISTS=pthread_create -g  -Wl,--fix-cortex-a8  -Wl,--gc-sections -Wl,-z,nocopyreloc  -pie  CMakeFiles/cmTC_37662.dir/CheckFunctionExists.c.o  -o cmTC_37662  -lpthreads 
/Users/samychen/Develop/android-ndk-r15c/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lpthreads
collect2: error: ld returned 1 exit status
make[1]: *** [cmTC_37662] Error 1
make[1]: Leaving directory `/Users/samychen/AndroidStudioProjects/ijkplayer/android/contrib/libsrt-armv7a/CMakeFiles/CMakeTmp'
make: *** [cmTC_37662/fast] Error 2

Determining if the function pthread_create exists in the pthread failed with the following output:
Change Dir: /Users/samychen/AndroidStudioProjects/ijkplayer/android/contrib/libsrt-armv7a/CMakeFiles/CMakeTmp

Run Build Command(s):/Users/samychen/AndroidStudioProjects/ijkplayer/android/contrib/build/toolchain-armv7a/bin/make cmTC_deb86/fast && /Users/samychen/AndroidStudioProjects/ijkplayer/android/contrib/build/toolchain-armv7a/bin/make -f CMakeFiles/cmTC_deb86.dir/build.make CMakeFiles/cmTC_deb86.dir/build
make[1]: Entering directory `/Users/samychen/AndroidStudioProjects/ijkplayer/android/contrib/libsrt-armv7a/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_deb86.dir/CheckFunctionExists.c.o
/Users/samychen/Develop/android-ndk-r15c/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-gcc --sysroot=/Users/samychen/Develop/android-ndk-r15c/sysroot  -isystem /Users/samychen/Develop/android-ndk-r15c/sysroot/usr/include -isystem /Users/samychen/Develop/android-ndk-r15c/sysroot/usr/include/arm-linux-androideabi  -fPIE -fPIC    -march=armv7-a -mthumb -mfpu=vfpv3-d16 -mfloat-abi=softfp -funwind-tables -no-canonical-prefixes -D__ANDROID_API__=14 -fexceptions -DCHECK_FUNCTION_EXISTS=pthread_create -g   -o CMakeFiles/cmTC_deb86.dir/CheckFunctionExists.c.o   -c /usr/local/Cellar/cmake/3.17.0_1/share/cmake/Modules/CheckFunctionExists.c
Linking C executable cmTC_deb86
/usr/local/Cellar/cmake/3.17.0_1/bin/cmake -E cmake_link_script CMakeFiles/cmTC_deb86.dir/link.txt --verbose=1
/Users/samychen/Develop/android-ndk-r15c/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-gcc --sysroot=/Users/samychen/Develop/android-ndk-r15c/platforms/android-14/arch-arm -fPIE -fPIC    -march=armv7-a -mthumb -mfpu=vfpv3-d16 -mfloat-abi=softfp -funwind-tables -no-canonical-prefixes -D__ANDROID_API__=14 -fexceptions -DCHECK_FUNCTION_EXISTS=pthread_create -g  -Wl,--fix-cortex-a8  -Wl,--gc-sections -Wl,-z,nocopyreloc  -pie  CMakeFiles/cmTC_deb86.dir/CheckFunctionExists.c.o  -o cmTC_deb86  -lpthread 
/Users/samychen/Develop/android-ndk-r15c/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lpthread
collect2: error: ld returned 1 exit status
make[1]: *** [cmTC_deb86] Error 1
make[1]: Leaving directory `/Users/samychen/AndroidStudioProjects/ijkplayer/android/contrib/libsrt-armv7a/CMakeFiles/CMakeTmp'
make: *** [cmTC_deb86/fast] Error 2

**Comment by befovy** [comment]
please use the latest build script
https://github.com/befovy/ijkplayer/blob/master/.github/workflows/android.yml shows how to build boringssl libsrt ffmpeg and ijkplayer
