### ISSUE TITLE
按照文档重新在本地编译 ijkplayer，得到 BUILD FAILED 错误

### ISSUE THREAD

**Issue by yang-he** [befovy/ijkplayer#47]
按照此[文档](https://fijkplayer.befovy.com/docs/zh/replace-ijkplayer.html#gsc.tab=0)为fijkplayer替换ijkplayer，执行
`xcodebuild -project IJKMediaPlayer.xcodeproj -configuration Release -scheme Universal` 后得到如下错误：

```
** BUILD FAILED **

The following build commands failed:
	CompileC /Users/yanghe/Library/Developer/Xcode/DerivedData/IJKMediaPlayer-grrptcvvqxxnmgfkmcizbnleddum/Build/Intermediates.noindex/IJKMediaPlayer.build/Release-iphoneos/IJKMediaPlayer.build/Objects-normal/arm64/allformats.o /Users/yanghe/Development/test/ijkplayer/ijkmedia/ijkplayer/ijkavformat/allformats.c normal arm64 c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
```

**Comment by befovy** [comment]
这个错误好像不完整。可以结合该文档以及 github action 配置来编译。

https://github.com/befovy/ijkplayer/actions/runs/156246096/workflow

action 配置是经过github action runner 验证过的，可以编译。我现在发版本也是用的 github action 这个环境

**Comment by yang-he** [comment]
> 这个错误好像不完整。可以结合该文档以及 github action 配置来编译。
> 
> https://github.com/befovy/ijkplayer/actions/runs/156246096/workflow
> 
> action 配置是经过github action runner 验证过的，可以编译。我现在发版本也是用的 github action 这个环境


我在本地重新编译替换 ijkplayer 的本意是需要支持 OpenSSL和（为了解决播放不了阿里云aes加密的m3u8视频的问题），从您的comment来看，您发的版本其实已经支持 openssl 了？

[阿里云媒体转码HLS标准加密详解](https://developer.aliyun.com/article/277348)

**Comment by befovy** [comment]
是的，我没打开 crypto
