### ISSUE TITLE
HLS master playalist: change stream without lag

### ISSUE THREAD

**Issue by minhtoantm** [befovy/ijkplayer#49]
Hi.
I tried but not found solution. can you tell me how to change stream without lag?
URL: https://mnmedias.api.telequebec.tv/m3u8/29880.m3u8

Thanks.

**Comment by befovy** [comment]
Please see [getTrackInfo](https://github.com/befovy/ijkplayer/blob/13af3d05b90b312edce790fd3812ba3c1962c1f0/android/ijkplayer/ijkplayer-java/src/main/java/tv/danmaku/ijk/media/player/IjkMediaPlayer.java#L657) and [selectTrack](https://github.com/befovy/ijkplayer/blob/13af3d05b90b312edce790fd3812ba3c1962c1f0/android/ijkplayer/ijkplayer-java/src/main/java/tv/danmaku/ijk/media/player/IjkMediaPlayer.java#L698) .
But it has lag. 
No other api to change stream

**Comment by minhtoantm** [comment]
Thank for your reply.
I know this method. I'm developing "hls bitrate adaptive", so it requires smooth change from low resolution to hight resolution smoothly.
Now, I don't have any solution....

**Comment by befovy** [comment]
But ijkplayer dose not support changing stream smoothly

**Comment by minhtoantm** [comment]
Thank for your reply.
