### ISSUE TITLE
跑iOS时， 一直会停止  pod install...

### ISSUE THREAD

**Issue by bear-zyy** [befovy/ijkplayer#5]

**Comment by bear-zyy** [comment]
停止pod install  后 会有
[!] `<PBXGroup UUID=`xxxxxxxxxxxx`>` attempted to initialize an object with an unknown UUID. `CF3B75C9A7D2FA2A4C99F110` for attribute: `children`. This can be the result of a merge and  the unknown UUID is being discarded.

**Comment by befovy** [comment]
@bear-zyy  你好， [befovy/ijkplayer](https://github.com/befovy/ijkplayer) 项目中的demo是没有用到 pod 依赖管理的，你是否是在使用 [fijkplayer](https://github.com/befovy/fijkplayer) ?
fijkplayer 中需要运行 pod install， 请加上 verbose 参数查看具体的pod 输出 `pod install --verbose`

**Comment by befovy** [comment]
@bear-zyy 请问还有其他补充信息吗？

**Comment by befovy** [comment]
如果还有什么问题，请重新打开
