### ISSUE TITLE
Enbale some audio decoder support

### ISSUE THREAD

**Issue by Vichet97** [befovy/ijkplayer#52]
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=mpeg4"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=mp2*"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=ac3"

**Comment by befovy** [comment]
Most users dose not need these decoders. You can build this decoders for yourself.
