### ISSUE TITLE
请问ijk是否支持iOS14的画中画功能？

### ISSUE THREAD

**Issue by DaiShuss** [befovy/ijkplayer#54]
是否支持呢？
如果没有的话，是否有引入支持画中画的打算？

**Comment by befovy** [comment]
你好，不支持画中画功能。

受 iOS 系统 API 限制，画中画只能给系统播放器 AVPlayer 使用。其他播放器要使用画中画功能需要自行破解一下私有API。
暂时没有支持画中画的打算。
