### ISSUE TITLE
bintray is shutting down

### ISSUE THREAD

**Issue by ened** [befovy/ijkplayer#60]
Please upload a new version of BIJKPlayer to a alternative CDN (google storage apis?)

Unfortunately, 
https://github.com/CocoaPods/Specs/blob/73d655c4d71297c7ba2625e735a46fdab891ffd8/Specs/6/f/0/BIJKPlayer/0.7.8/BIJKPlayer.podspec.json currently points to https://dl.bintray.com/befovytray/bijkplayer/f0.7.8/IJKMediaPlayer.tar.gz and that URL is returning 403 (Forbidden).

https://github.com/befovy/fijkplayer/issues/391

**Comment by befovy** [comment]
please use new version
