### ISSUE TITLE
compile-ffmpeg.sh all这步报错

### ISSUE THREAD

**Issue by ProgramerMartin** [befovy/ijkplayer#75]
/ijkplayer-android/android/contrib/build/ffmpeg-armv7a/toolchain/bin//arm-linux-androideabi-gcc
arm-linux-androideabi-gcc is unable to create an executable file.
C compiler test failed.

**Comment by befovy** [comment]
follow the step in github action
https://github.com/befovy/ijkplayer/blob/master/.github/workflows/android.yml

If still failed, please provide a log
