### ISSUE TITLE
编译发生错误，错误log如下，请问有什么解决方案吗

### ISSUE THREAD

**Issue by kwcn** [befovy/ijkplayer#8]
cmake --build D:\Download\ijk-befovy\ijkplayer-android\android\ijkplayer\fijkplayer-full\.externalNativeBuild\cmake\debug\armeabi-v7a --target ijkplayer
[32/109] cmd.exe /C "cd /D D:\Download\ijk-befovy\ijkplaye...ayer-full\build\intermediates\cmake\debug\obj\armeabi-v7a"
FAILED: cmd.exe /C "cd /D D:\Download\ijk-befovy\ijkplayer-android\android\ijkplayer\fijkplayer-full\.externalNativeBuild\cmake\debug\armeabi-v7a && mkdir -p D:\Download\ijk-befovy\ijkplayer-android\android\ijkplayer\fijkplayer-full\build\intermediates\cmake\debug\obj\armeabi-v7a && cp D:/Download/ijk-befovy/ijkplayer-android/android/contrib/build/ffmpeg-armv7a/output/libijkffmpeg.so D:\Download\ijk-befovy\ijkplayer-android\android\ijkplayer\fijkplayer-full\build\intermediates\cmake\debug\obj\armeabi-v7a"
子目录或文件 -p 已经存在。
处理: -p 时出错。
子目录或文件 D:\Download\ijk-befovy\ijkplayer-android\android\ijkplayer\fijkplayer-full\build\intermediates\cmake\debug\obj\armeabi-v7a 已经存在。
处理: D:\Download\ijk-befovy\ijkplayer-android\android\ijkplayer\fijkplayer-full\build\intermediates\cmake\debug\obj\armeabi-v7a 时出错。
[32/109] Linking CXX static library ijkmedia\ijkyuv\libyuv_static.a
ninja: build stopped: subcommand failed.

**Comment by befovy** [comment]
麻烦补充一下你的编译步骤？ 每一步使用什么命令

**Comment by kwcn** [comment]
> 麻烦补充一下你的编译步骤？ 每一步使用什么命令
按照提示操作完下面命令：
git clone https://github.com/befovy/ijkplayer.git ijkplayer-android
cd ijkplayer-android

./init-android.sh

cd android/contrib
./compile-ffmpeg.sh clean
./compile-ffmpeg.sh all

然后运行Android studio就报上面的错误，一直编不过，ndk是15的，windows环境

**Comment by befovy** [comment]
![image](https://user-images.githubusercontent.com/51129600/67380657-4367a200-f5bd-11e9-8dae-554507794203.png)

运行过这个吗？

或者删除下面两个文件夹

![image](https://user-images.githubusercontent.com/51129600/67380860-89bd0100-f5bd-11e9-87ee-ddd037c4205d.png)

然后运行 `./gradlew :fijkplayer-full:assembleRelease`

**Comment by kwcn** [comment]
@befovy 这样做之后还是报错
![E27ED06F-4C2F-4369-8182-C0FD3D248BDA](https://user-images.githubusercontent.com/20631795/67383811-84ae8080-f5c2-11e9-952d-803b348dab47.png)
Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.1.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 49s
19 actionable tasks: 18 executed, 1 up-to-date

会不会因为是windows环境的原因

**Comment by befovy** [comment]
你安装 cmake 了吗？ windows 系统上我确实没试过


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by kwcn** [comment]
@befovy 本来安装的是3.10，不知道为啥跑你的代码都会自动安装一个3.6。难道mac和windows上执行cmd的一些命令不一样

**Comment by befovy** [comment]
仔细看了一下，是这里出错了


add_custom_target(cpffmpeg
    COMMAND mkdir -p ${CMAKE_LIBRARY_OUTPUT_DIRECTORY}
    COMMAND cp ${FFMPAG_SHARED_DIR}/libijkffmpeg.so ${CMAKE_LIBRARY_OUTPUT_DIRECTORY}
)


 Windows 没有 mkdir -p


你可以删除这一段，手动执行 创建文件夹自己复制动作。

欢迎pr


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by kwcn** [comment]
cmake是安装的，看上面错误是在执行 mkdir -p发生的错误，请问一下这个创建文件，复制so文件的命令是在哪个文件夹里写的呢

**Comment by kwcn** [comment]
删除了之后又报这个错误，看样子是 ijkversion文件不在了：

FAILED: D:\Download\android-ndk-r15c-windows-x86_64\android-ndk-r15c\toolchains\x86_64-4.9\prebuilt\windows-x86_64\bin\x86_64-linux-android-gcc.exe  --sysroot=D:
/Download/android-ndk-r15c-windows-x86_64/android-ndk-r15c/sysroot -DANDROID -DNDEBUG -Dijkplayer_EXPORTS -ID:/Download/ijk-befovy/ijk_befovy/ijkplayer-android/ijk
media/ijkplayer -ID:/Download/ijk-befovy/ijk_befovy/ijkplayer-android/ijkmedia/ijkplayer/.. -ID:/Download/ijk-befovy/ijk_befovy/ijkplayer-android/android/contrib/b
uild/ffmpeg-x86_64/output/include -ID:/Download/ijk-befovy/ijk_befovy/ijkplayer-android/ijkmedia/ijkplayer/ijkavformat -ID:/Download/ijk-befovy/ijk_befovy/ijkplaye
r-android/ijkmedia/ijkplayer/ijkavutil -ID:/Download/ijk-befovy/ijk_befovy/ijkplayer-android/ijkmedia/ijkplayer/pipeline -ID:/Download/ijk-befovy/ijk_befovy/ijkpla
yer-android/ijkmedia/ijkplayer/../ijkj4a -isystem D:/Download/android-ndk-r15c-windows-x86_64/android-ndk-r15c/sysroot/usr/include/x86_64-linux-android -D__ANDROID
_API__=21 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Wa,--noexecstack -Wformat -Werror=format-security  -O2
-DNDEBUG  -fPIC   -std=gnu11 -MD -MT ijkmedia/ijkplayer/CMakeFiles/ijkplayer.dir/ijkplayer.c.o -MF ijkmedia\ijkplayer\CMakeFiles\ijkplayer.dir\ijkplayer.c.o.d -o i
jkmedia/ijkplayer/CMakeFiles/ijkplayer.dir/ijkplayer.c.o   -c D:\Download\ijk-befovy\ijk_befovy\ijkplayer-android\ijkmedia\ijkplayer\ijkplayer.c
  D:\Download\ijk-befovy\ijk_befovy\ijkplayer-android\ijkmedia\ijkplayer\ijkplayer.c:26:24: fatal error: ijkversion.h: No such file or directory

   #include "ijkversion.h"

                          ^

  compilation terminated.

  ninja: build stopped: subcommand failed.

**Comment by befovy** [comment]
ijkversion.h 是自动生成的，不在git 中记录。可能生成 ijkversion.h的命令windows 上也不行


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by kwcn** [comment]
什么命令呢，这步能手动完成吗？

**Comment by befovy** [comment]
正在路上，等我回去给你发个文件。可以加我微信 befovy


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by kwcn** [comment]
好的，麻烦您了

**Comment by befovy** [comment]
```c
/* Automatically generated by version.sh, do not manually edit! */
#ifndef IJKVERSION_H
#define IJKVERSION_H
#define IJKPLAYER_VERSION "f0.3.8-2-gc5ef8361"
#endif /* IJKVERSION_H */
```

ijkversion.h 的全部内容。
文件位于 ijkmedia/ijkplayer 内

**Comment by kwcn** [comment]
加了ijkversion.h后，又有新的cmd命令错误 ，好像bash出现了问题：
FAILED: cmd.exe /C "cmd.exe /C "cd /D D:\Download\ijk-befovy\ijk_befovy\ijkplayer-android\android\ijkplayer\fijkplayer-full\.externalNativeBuild\cmake\release\x8
6_64\ijkmedia\ijkplayer && bash D:/Download/ijk-befovy/ijk_befovy/ijkplayer-android/ijkmedia/ijkplayer/version.sh D:/Download/ijk-befovy/ijk_befovy/ijkplayer-andro
id/ijkmedia/ijkplayer ijkversion.h && cd D:\Download\ijk-befovy\ijk_befovy\ijkplayer-android\android\ijkplayer\fijkplayer-full\.externalNativeBuild\cmake\release\x
86_64" && D:\Download\android-ndk-r15c-windows-x86_64\android-ndk-r15c\toolchains\x86_64-4.9\prebuilt\windows-x86_64\bin\x86_64-linux-android-g++.exe  --sysroot=D:
/Download/android-ndk-r15c-windows-x86_64/android-ndk-r15c/sysroot -fPIC -isystem D:/Download/android-ndk-r15c-windows-x86_64/android-ndk-r15c/sysroot/usr/include/
x86_64-linux-android -D__ANDROID_API__=21 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Wa,--noexecstack -Wform
at -Werror=format-security -std=c++11 -fno-strict-aliasing  -O2 -DNDEBUG  -Wl,--exclude-libs,libgcc.a --sysroot D:/Download/android-ndk-r15c-windows-x86_64/android
-ndk-r15c/platforms/android-21/arch-x86_64 -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -LD:/Download/android-ndk-r15c-windows-x86_64/android-ndk-
r15c/sources/cxx-stl/llvm-libc++/libs/x86_64 -Wl,--no-undefined -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -shared -Wl,-soname,libijkplayer.so -o D:\Download\ijk-b
efovy\ijk_befovy\ijkplayer-android\android\ijkplayer\fijkplayer-full\build\intermediates\cmake\release\obj\x86_64\libijkplayer.so ijkmedia/ijkplayer/CMakeFiles/ijk
player.dir/ff_cmdutils.c.o ijkmedia/ijkplayer/CMakeFiles/ijkplayer.dir/ff_ffplay.c.o ijkmedia/ijkplayer/CMakeFiles/ijkplayer.dir/ff_ffpipeline.c.o ijkmedia/ijkplay
er/CMakeFiles/ijkplayer.dir/ff_ffpipenode.c.o ijkmedia/ijkplayer/CMakeFiles/ijkplayer.dir/ijkmeta.c.o ijkmedia/ijkplayer/CMakeFiles/ijkplayer.dir/ijkplayer.c.o ijk
media/ijkplayer/CMakeFiles/ijkplayer.dir/pipeline/ffpipeline_ffplay.c.o ijkmedia/ijkplayer/CMakeFiles/ijkplayer.dir/pipeline/ffpipenode_ffplay_vdec.c.o ijkmedia/ij
kplayer/CMakeFiles/ijkplayer.dir/ijkavformat/allformats.c.o ijkmedia/ijkplayer/CMakeFiles/ijkplayer.dir/ijkavformat/ijklivehook.c.o ijkmedia/ijkplayer/CMakeFiles/i
jkplayer.dir/ijkavformat/ijkmediadatasource.c.o ijkmedia/ijkplayer/CMakeFiles/ijkplayer.dir/ijkavformat/ijkio.c.o ijkmedia/ijkplayer/CMakeFiles/ijkplayer.dir/ijkav
format/ijkiomanager.c.o ijkmedia/ijkplayer/CMakeFiles/ijkplayer.dir/ijkavformat/ijkiocache.c.o ijkmedia/ijkplayer/CMakeFiles/ijkplayer.dir/ijkavformat/ijkioffio.c.
o ijkmedia/ijkplayer/CMakeFiles/ijkplayer.dir/ijkavformat/ijkioprotocol.c.o ijkmedia/ijkplayer/CMakeFiles/ijkplayer.dir/ijkavformat/ijkioapplication.c.o ijkmedia/i
jkplayer/CMakeFiles/ijkplayer.dir/ijkavformat/ijkiourlhook.c.o ijkmedia/ijkplayer/CMakeFiles/ijkplayer.dir/ijkavformat/ijkasync.c.o ijkmedia/ijkplayer/CMakeFiles/i
jkplayer.dir/ijkavformat/ijkurlhook.c.o ijkmedia/ijkplayer/CMakeFiles/ijkplayer.dir/ijkavformat/ijklongurl.c.o ijkmedia/ijkplayer/CMakeFiles/ijkplayer.dir/ijkavfor
mat/ijksegment.c.o ijkmedia/ijkplayer/CMakeFiles/ijkplayer.dir/ijkavutil/ijkdict.c.o ijkmedia/ijkplayer/CMakeFiles/ijkplayer.dir/ijkavutil/ijkutils.c.o ijkmedia/ij
kplayer/CMakeFiles/ijkplayer.dir/ijkavutil/ijkthreadpool.c.o ijkmedia/ijkplayer/CMakeFiles/ijkplayer.dir/ijkavutil/ijktree.c.o ijkmedia/ijkplayer/CMakeFiles/ijkpla
yer.dir/ijkavutil/ijkfifo.c.o ijkmedia/ijkplayer/CMakeFiles/ijkplayer.dir/ijkavutil/ijkstl.cpp.o ijkmedia/ijkplayer/CMakeFiles/ijkplayer.dir/ijkavformat/ijkioandro
idio.c.o ijkmedia/ijkplayer/CMakeFiles/ijkplayer.dir/android/ffmpeg_api_jni.c.o ijkmedia/ijkplayer/CMakeFiles/ijkplayer.dir/android/ijkplayer_android.c.o ijkmedia/
ijkplayer/CMakeFiles/ijkplayer.dir/android/ijkplayer_jni.c.o ijkmedia/ijkplayer/CMakeFiles/ijkplayer.dir/android/pipeline/ffpipeline_android.c.o ijkmedia/ijkplayer
/CMakeFiles/ijkplayer.dir/android/pipeline/ffpipenode_android_mediacodec_vdec.c.o  D:/Download/ijk-befovy/ijk_befovy/ijkplayer-android/android/ijkplayer/fijkplayer
-full/build/intermediates/cmake/release/obj/x86_64/libijksdl.so ijkmedia/ijksoundtouch/libijksoundtouch.a D:/Download/ijk-befovy/ijk_befovy/ijkplayer-android/andro
id/contrib/build/ffmpeg-x86_64/output/libijkffmpeg.so ijkmedia/ijkprof/libandroid-ndk-profiler.a -llog -landroid ijkmedia/ijkj4a/libijkj4a.a ijkmedia/ijkyuv/libyuv
_static.a -lOpenSLES -lEGL -lGLESv2 -lm "D:/Download/android-ndk-r15c-windows-x86_64/android-ndk-r15c/sources/cxx-stl/llvm-libc++/libs/x86_64/libc++.a" && cd ."
  'bash' ????????????????????????е????

**Comment by kwcn** [comment]
ijkmedia/ijkplayer 内的CmakeLists文件删除下面内容就好了：

#add_custom_command(TARGET ijkplayer
#    PRE_BUILD
#    COMMAND bash ${CMAKE_CURRENT_LIST_DIR}/version.sh ${CMAKE_CURRENT_LIST_DIR} ijkversion.h
#)

**Comment by befovy** [comment]
```cmake
add_custom_command(TARGET ijkplayer
    PRE_BUILD
    COMMAND bash ${CMAKE_CURRENT_LIST_DIR}/version.sh ${CMAKE_CURRENT_LIST_DIR} ijkversion.h
)
```
这个是运行 shell 脚本生成 ijkversion.h 的步骤，windows 上不支持，需要删除

**Comment by kwcn** [comment]
@befovy 编译成功了，十分感谢

**Comment by ZhuBoao** [comment]
@befovy 我在macOS下跑`./gradlew :fijkplayer-full:assembleRelease`，一样的问题，找不到`ijkversion.h`。手动跑了`version.sh`生成后再跑gradlew成功编译了。不清楚是不是CMake调用`version.sh`时没成功，CMake我太不熟了不清楚怎么调试，大佬有空的话可以看下是不是还存在这个问题。
